[package]
name = "midi2swstruct"
version = "0.2.11"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
midly = "0.5.3"
num-traits = "0.2.19"
sw-structure-io = { git = "https://github.com/nukecat/sw-structure-io.git" }
thiserror = "2.0.18"
